---
- name: Bootstrap the hosts to trust the CA
  ansible.builtin.include_role:
    name: maxhoesel.smallstep.step_bootstrap_host
  vars:
    step_bootstrap_ca_url: "{{ acme_fqdn }}"
    step_bootstrap_fingerprint: "{{ acme_fingerprint }}"
    step_bootstrap_force: true # temp fdo 20221122
  when:
    - step_bootstrap_ca is not defined and not step_bootstrap_ca
    - acme_fqdn is defined 
    - acme_fqdn | length > 0
...
