---
- name: Bootstrap the hosts to trust the CA
  ansible.builtin.include_role:
    name: maxhoesel.smallstep.step_bootstrap_host
  vars:
    step_bootstrap_ca_url: "{{ acme_fqdn }}"
    step_bootstrap_fingerprint: "{{ acme_fingerprint }}"
  when: acme_fqdn is defined and acme_fqdn|length>0
...
