---
- name: Run step_acme_cert
  ansible.builtin.include_role:
    name: maxhoesel.smallstep.step_acme_cert
  vars:
    step_acme_cert_certfile: "{{ acme_tls_cert_certfile }}"
    step_acme_cert_keyfile: "{{ acme_tls_cert_keyfile }}"
    step_acme_cert_webroot_path: "{{ acme_tls_cert_webroot_path }}"
    step_acme_cert_contact: "{{ acme_tls_cert_contact }}"
    step_acme_cert_renewal_reload_services: "{{ acme_tls_cert_reload_services }}"
    step_acme_cert_ca_provisioner: "{{ acme_provisioner }}"
  when: 
    - step_bootstrap_ca is not defined and not step_bootstrap_ca
    - acme_fqdn is defined 
    - acme_fqdn | length > 0
...
