---
- name: CA Tests 
  block:
    - name: Populate service facts
      service_facts:
      register: service_state
      delegate_to: "{{ ca.fqdn if ca is defined and ca.url|bool }}"

    - name: check if ca service is down is a critical error
      fail:
        msg: "The CA cannot be reached and no certificate can be issued."
      when:
        - service_state.ansible_facts.services['step-ca.service'] is not defined
        - skip_cert_if_ca_down | bool != true

    - name: ca is down no critical failure
      fail:
        msg: "The CA cannot be reached and no certificate can be issued, this step is skipped."
      when:
        - service_state.ansible_facts.services['step-ca.service'] is not defined
        - skip_cert_if_ca_down | bool == true
      ignore_errors: true

    - name: Verify that the communication to the bodomos-ca is working
      command: step-cli ca health
      changed_when: no
      when: service_state.ansible_facts.services['step-ca.service'] is defined
  when: ca is defined and ca.url|bool
...