---
- name: Copy Certificates as zip in local certificate store
  block:
    - name: Create temp directory for Certificates
      ansible.builtin.tempfile:
        state: directory
        suffix: temp
      register: tempfilepath

    - name: Download Certificate ZIP
      ansible.builtin.get_url:
        url: "{{ crt_zip_download_url }}"
        dest: "{{ tempfilepath.path }}/crt.zip"
        validate_certs: false
        mode: '0400'

    - name: Extract /usr/local/share/ca-certificates
      ansible.builtin.unarchive:
        src: "{{ tempfilepath.path }}/crt.zip"
        dest: /usr/local/share/ca-certificates
        remote_src: true

    - name: Update-ca-certificates  # noqa no-changed-when
      ansible.builtin.command:
        cmd: "/usr/sbin/update-ca-certificates"

  always:
    - name: Cleanup temp
      ansible.builtin.file:
        path: "{{ tempfilepath.path }}"
        state: absent
  when: crt_zip_download_url is defined and crt_zip_download_url | length > 0
...
