---
#
#                    ┌───────┐
#                    │ Start │
#                    └───┬───┘
#                        │
#        ┌─────┐         │        ┌───────┐
#        │ URL ◄─────────┴────────► local │
#        └──┬──┘                  └───┬───┘
#           │                         │
#  ┌─────┐  │   ┌──────┐    ┌─────┐   │    ┌──────┐
#  │ ZIP ◄──┴───► File │    │ ZIP ◄───┴────► File │
#  └─────┘      └──────┘    └─────┘        └──────┘

- name: Copy Certificates in local certificate store
  block:
    - name: Create temp directory for Certificates
      ansible.builtin.tempfile:
        state: directory
        suffix: temp
      register: tempfilepath_cert

    # If "http://" in "ca_certificates" and the filetype is zip -> download.
    # The second step in this case is to decompress the zip.
    - name: Download certificate-zip from URL
      ansible.builtin.get_url:
        url: "{{ ca_certificates }}"
        dest: "{{ tempfilepath_cert.path }}/crt.zip"
        validate_certs: false
        mode: '0400'
      when:
        - ca_certificates is defined
        - ca_certificates | length > 0
        - ca_certificates is match("http://") or ca_certificates is match("https://") # match succeeds if it finds the pattern at the beginning of the string
        - ca_certificates is search(".zip")
      notify:
        - Import_certificates - unzip and copy

    # If "http://" is not in "ca_certificates" and the filetype is zip. -> local-zip-file
    # The second step in this case is to decompress the zip.
    - name: Copy certificates-zip from local absolute-path
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ tempfilepath_cert.path }}/crt.zip"
        mode: '0600'
      with_items: "{{ ca_certificates }}"
      when:
        - ca_certificates is defined
        - ca_certificates | length > 0
        - ca_certificates is not match("http://") and ca_certificates is not match("https://")
        - ca_certificates is search(".zip")
        - (ca_certificates is string) # https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#type-tests
      notify:
        - Import_certificates - unzip and copy

    # If "http://" in "ca_certificates" and the vartype of "ca_certificates" is _list_ or _string_. -> download
    # The certificates are copied directly to the target directory.
    - name: Download list of certificates from URL
      ansible.builtin.get_url:
        url: "{{ item }}"
        dest: "{{ ca_cert_destination }}"
        mode: '0644'
      with_items: "{{ ca_certificates }}"
      when:
        - ca_certificates is defined
        - ca_certificates | length > 0
        # match succeeds if it finds the pattern at the beginning of the string
        - ca_certificates is match("http://") or ca_certificates is match("https://")
        - ca_certificates is not search(".zip")
        # https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#type-tests
        - (ca_certificates is string) or (ca_certificates is not string and ca_certificates is not mapping and ca_certificates is iterable)
      notify:
        - Import_certificates - update trusted ca debian

    # If "http://" is not in "ca_certificates" and the vartype of "ca_certificates" is _list_ or _string_. -> local certificates
    # The certificates are copied directly to the target directory.
    - name: Copy list of certificates from local absolute-path
      ansible.builtin.copy:
        src: "{{ item }}"
        dest: "{{ ca_cert_destination }}"
        mode: '0644'
      with_items: "{{ ca_certificates }}"
      when:
        - ca_certificates is defined
        - ca_certificates | length > 0
        - ca_certificates is not match("http://") and ca_certificates is not match("https://")
        - ca_certificates is not search(".zip")
        # https://docs.ansible.com/ansible/latest/user_guide/playbooks_tests.html#type-tests
        - (ca_certificates is string) or (ca_certificates is not string and ca_certificates is not mapping and ca_certificates is iterable)
      notify:
        - Import_certificates - update trusted ca debian
  when: ca_certificates is defined and ca_certificates | length > 0
...
