---
- name: Set SSH loglevel to verbose
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#LogLevel INFO"
    line: "LogLevel VERBOSE"

- name: Disable SSH root login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#PermitRootLogin"
    line: "PermitRootLogin no"

- name: Disable empty passwords
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^#PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"

- name: Enable SSH password authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication yes"

- name: Set SSH UsePrivilegeSeparation
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: "UsePrivilegeSeparation sandbox"

- name: Set AllowGroups
  # grupnames with whitspaces are supported´
  # add "adm" group by default so every user of group "adm" is allowed to connect
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    state: present
    line: "AllowGroups adm {{ sshd_allowgroups | map('quote') | join(' ') }}"
  when: sshd_allowgroups is defined and sshd_allowgroups | length > 0

- name: Restart services
  block:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Restart sshd
      ansible.builtin.systemd:
        name: "{{ item }}"
        state: restarted
        enabled: true
        masked: false
        daemon_reload: true
      when: "item in services"
      with_items:
        - sshd.service
...
