---
- name: add sudo users
  community.general.sudoers:
    name: "{{ item }}"
    state: present
    user: "{{ item }}"
    nopassword: no
    runas: All
    commands: All
  with_items: "{{ sudo_users }}"
  when: sudo_users is defined and sudo_users|length>0

- name: add sudo groups
  community.general.sudoers:
    name: "{{ item }}"
    state: present
    group: "{{ item }}"
    nopassword: no
    runas: All
    commands: All
  with_items: "{{ sudo_groups }}"
  when: sudo_groups is defined and sudo_groups|length>0
...
