---
- name: Add sudo users
  community.general.sudoers:
    name: "{{ item }}"
    state: present
    user: "{{ item }}"
    nopassword: false
    runas: ALL
    commands: ALL
  with_items: "{{ sudo_users }}"
  when: sudo_users is defined and sudo_users | length > 0

- name: Add sudo groups
  community.general.sudoers:
    name: "{{ item | replace(' ', '^')}}" # Fix visudoers problems in ubuntu 22.10
    state: present
    group: "{{ item | replace(' ', '^')}}"
    nopassword: false
    runas: ALL
    commands: ALL
  with_items: "{{ sudo_groups }}"
  when: sudo_groups is defined and sudo_groups | length > 0
...
